# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: to-do-app/node_modules
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('to-do-app/package-lock.json') }}
        restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        cd to-do-app
        npm ci
    - name: Build project
      run: |
        cd to-do-app
        npm run build --if-present
    - name: Run tests
      run: |
        cd to-do-app
        npm test
    - name: Create deploy folder and add version info
      if: matrix.node-version == '20.x' && github.ref == 'refs/heads/main'
      run: |
        mkdir -p deploy
        echo "Version: $(node -p \"require('./package.json').version\")" > deploy/version.txt
        cp -r build/* deploy/
